export const StakeWinsTableProps = {
    columns: ["TYPE", "RACE", "YEAR", "LOCATION", "DISTANCE", "TRACK"],
    displayColumns: ["type", "race", "year", "location", "distance", "track"],
    tableIdentifier: "PROGENY",
    hascolumnDivider: true,
    data: [{ id: "0", type:"G1", race:"Nassau Stakes", year:"2011", location:"Great Britain", distance: "10 Fur", track: "Turf" },
           { id: "1", type:"G1", race:"Yorkshire Oaks", year:"2010", location:"Great Britain", distance:"10 Fur", track: "Turf" },
           { id: "2", type:"G1", race:"Nassau Stakes", year:"2010", location:"Great Britain", distance:"10 Fur", track: "Turf" },
           { id: "3", type:"G1", race:"Prix Vermeille", year:"2010", location:"France", distance:"10 Fur", track: "Turf" },
           { id: "4", type:"G1", race:"Nassau Stakes", year:"2009", location:"Great Britain", distance:"10 Fur", track: "Turf" },
           { id: "5", type:"G1", race:"Breeders Cup Filly & Mare", year:"2011", location:"Great Britain", distance:"10 Fur", track: "Turf" },
           { id: "6", type:"G1", race:"Middleton Stakes", year:"2009", location:"USA", distance:"10 Fur", track: "Turf" },
           { id: "7", type:"G1", race:"Nassau Stakes", year:"2011", location:"USA", distance:"10 Fur", track: "Turf" },
           { id: "8", type:"G1", race:"Yorkshire Oaks", year:"2011", location:"Great Britain", distance:"10 Fur", track: "Turf" },
           { id: "9", type:"G1", race:"Prix Vermeille", year:"2011", location:"France", distance:"10 Fur", track: "Turf" },
           { id: "10", type:"G1", race:"Middleton Stakes", year:"2011", location:"France", distance:"10 Fur", track: "Turf" },
           { id: "11", type:"G1", race:"Prix Vermeille", year:"2011", location:"Great Britain", distance:"10 Fur", track: "Turf" },
           { id: "12", type:"G1", race:"Yorkshire Oaks", year:"2009", location:"France", distance:"10 Fur", track: "Turf" },
           { id: "13", type:"G1", race:"Middleton Stakes", year:"2009", location:"Great Britain", distance:"10 Fur", track: "Turf" },
           { id: "14", type:"G1", race:"Yorkshire Oaks", year:"2011", location:"USA", distance:"10 Fur", track: "Turf" },
        ],
    hasAvatar: false
}