import { createApi, fetchBaseQuery } from '@reduxjs/toolkit/query/react';
import { api } from 'src/api/apiPaths';

const accessToken = localStorage.getItem('accessToken');

export const emptySplitApi = createApi({
  reducerPath: 'splitApi',
  baseQuery: fetchBaseQuery({
    baseUrl: 'https://',
  }),
  tagTypes: [
    'Validate Link',
    'UpdateEmail',
    'testimonials',
    'States',
    'stallionShortlist',
    'stallionRoster',
    'StallionMare',
    'stallions',
    'searchStallionNames',
    'SearchSires',
    'searchMareNames',
    'searchDamSires',
    'farmsAdd',
    'addEmailSubscription',
    'stallionsAdd',
    'AddToFavoriteDamsires',
    'AddToFavoriteFarms',
    'AddToFavoriteStallions',
    'AddToFavoriteStallions',
    'AllStates',
    'Country',
    'stallionsCreate',
    'CartItems',
    'DeleteFromFavoriteDamsires',
    'DeleteFromFavoriteFarms',
    'DeleteFromFavoriteStallions',
    'farms',
    'favouriteMares',
    'favouriteStallions',
    'Forgot Password',
    'Colours',
    'Currencies',
    'CurrencyRates',
    'Damsires',
    'GetFarmById',
    'Farms',
    'AuthFarmlist',
    'FarmsInFilter',
    'FarmStallions',
    'FavoriteDamsires Table',
    'FavoriteFarms Table',
    'FavoriteStallions',
    'homepageStats',
    'Mares',
    'Notification',
    'getStallionByCountry',
    'stallionDetails',
    'Stallions',
    'Testimonials',
    'YearToStud',
    'guestStallionShortlist',
    'Invite User',
    'Login',
    'MarePedigree',
    'PatchStallionDetailsById',
    'Pedigree',
    'Register',
    'registerInterest',
    'registerInterestEmail',
    'reportEmailValidation',
    'Resend Link',
    'Reset Password',
    'serviceFeeByYear',
    'PatchFarmDetailsById',
    'matchedMares',
    'progenyTrackerSR',
    'progenyTrackerSP',
    'raceRecords',
    'stakesWinnersComparision',
    'farmProfileImageUpload',
    'AlternateMatingSuggestions',
    'stallionProfileImageUpload',
    'MyMares Table',
    'Favorite Stallion Table',
    'Farm Media',
    'stallionGalleryimage',
    'stallionTestimonials',
    'searchBroodmareSireNames',
    'searchFarmByName',
    'InviteUsers Table',
    'User Name',
    'User Email',
    'User Address',
    'InviteUsers Table',
    'stallionSelection',
    'farmDetails',
    'farmGalleryimage',
    'farmMedias',
    'FarmUsersList',
    'Recent Searches',
    'Delete Farm',
    'AuthMe',
    'My Horses',
    'currenciesMinMaxvalue',
    'Get MareLists CSV',
    'MessageFarmList',
    'PostMessageFarmList',
    'Message Count',
    'Notification Count',
    'Race Records',
    'Stakes Progeny',
    'AllMessages',
    'getAllstallions',
    'getProducts',
    'MessageUnReadCount',
    'Fee Suggestion',
    'stallionsPromotedByFarmId',
    'MessageFarmListFarmAdmin',
    'getEnquiredFarms',
    'Nomination Availability',
    'Interests',
    'NominationRequestPost',
    'Notification Preferences',
    'Latest Messages',
    'Latest User Messages',
    'Discount',
    'GET LATEST ORDER',
    'Order History',
    'Marketing',
    'Farm Media',
    'DeleteMessage',
    'PatchNominationOffer',
    'FarmMembers',
    'PostUnRegisteredMessage',
    'Sire By Name',
    'Grand Sire By Name',
    'Dam Sire By Name',
    'PostUnRegisteredMessage',
    'PostGetChannelId',
    'useMediaUploadStatusMutation',
    'popular-stallions',
    'similar-stallions',
    'compatible-stallions',
    'Download MareList',
    'PatchMessageRead',
    'NominationRequestPostUnregistered',
    'Download MareList Template',
    'Most Searched Stallions',
    'Recent Stallion Searches',
    'stallion match',
    'auth stallion match',
    'profileDetails',
    'Most Popular Stallion',
    'Top Performing Stallion',
    'Most Popular Damsire',
    'Top 10 20/20 Matched Sires',
    'Farm Activity',
    'Top 10 20/20 Matched Broodmare Sires',
    'Most Matched Damsires',
    'Hottest Cross',
    'ChannelState',
    'profileDetails',
    'getSelectStallions',
    'getProjectReportsData',
    'stallionOverview',
    'aptitudeProfile',
    'breederMatchedMares',
    'AuthUserDetails',
    'progenyTracker',
    'Top Matched Sires',
    'InvitaionGetHash',
    'AcceptInvitation',
    'Stallions Matched Activity trends',
    'PostCreateChannelId',
    'getdownloadBreederReport',
    'boostCart',
    'Top Ten Perfect Matched Sires',
    'Top 10 Perfect Matched BroodMare Sires',
    'Page Data',
    'farmOverview',
    'mailPreview',
    'horseDetails',
    'Stallion Activity',
    'Stallion Match Activity',
    'Stallion Analytics',
    'getAllStallionLocations',
    'getAllFarmLocations',
    'Home page session count',
    'MessageAddChannelId',
    'PatchMessageRestore',
    'RaceHorsePedigree'
  ],
  endpoints: () => ({}),
});

export const splitApi = emptySplitApi;
